### PR TITLE
update mrpro example

### PR DESCRIPTION
**Pull request by fzimmermann89**
Hi,

Patrick @schuenke told me about your paper. This is an improved example of using MRpro with simulated data.
Note, that the "KData" machinery relies on a valid ISMRMRD header. If a simulator writes valid headers, reconstruction is 
a lot simpler.

But this current example already show cases some nice features, such as automatic resorting of the data -- which makes it at least a tiny bit superior in one regard to the other reconstruction examples ;)

Good luck finishing the paper,
Felix

### CODE REVIEW

**Comment by schuenke** [comment]
Here is also a working jupyter notebook link:
https://colab.research.google.com/drive/12p1wTj0gQLw8-AKRhqKv-EINwcEdKSiu?usp=sharing

The MRpro recon also works for centric reordering, where the others currently still fail.

**Comment by jtamir** [comment]
Just wanted to thank you for working on this!

**Comment by mzaiss** [comment]
Yes, thanks a lot!

We already submitted, but we will add the citation of MRpro https://doi.org/10.5281/zenodo.14509599 
during the revision process.

**Comment by mzaiss** [comment]
I have one remaining issue
IfIrun the cell twice the mrpro install command drops an error

Also 

!pip show mrpro || pip install mrpro &> /dev/null

Does notify it, already pip show mrpro drops an error…

**Comment by schuenke** [comment]
I can have a look tomorrow. Dont have a PC tonight. But maybe @fzimmermann89 can try to reproduce the error?!

**Comment by fzimmermann89** [comment]
This is something strange with colab. https://github.com/googlecolab/colabtools/issues/3409

The issue is not really related to the `pip instal`l.
No `!commands` work after this line
`plt.matshow(img.squeeze().abs().numpy(force=True), cmap='gray')`
because the locale changed somewhere.

**Comment by fzimmermann89** [comment]
reproducer:
in a new colab runtime(!)
```
import torch
a=torch.ones(1,2).cuda()+1j
a.squeeze().abs()
!echo "cake is a lie"
```

causes an issue.
restarting the session fixes it. and keeps it fixed.
so only on the first run with a fresh "runtime" (i.e. container or whatever colab uses) it causes an issue. 🤪

**Comment by mzaiss** [comment]
wonderful.
colab seems to be the perfect tool for pushing reproducible research ... 

thanks for testing!

**Comment by fzimmermann89** [comment]
```
import torch
a=torch.tensor(1j,device="cuda")
a.abs()
!echo "cake is a lie"
```

**Comment by fzimmermann89** [comment]
and putting
```
import locale
locale.getpreferredencoding = lambda: "UTF-8"

```
somewhere "fixes" it.
this can be run before the .abs() call... Or after.


or putting a `.cpu` before the abs should also fix it
`plt.matshow(img.cpu().squeeze().abs(), cmap='gray')`

**Comment by mzaiss** [comment]
so i move now to numpy earlier, as we normally do also for plotting.

and this resolves it.

img=img.cpu().numpy()
plt.matshow(np.abs(img.squeeze()), cmap='gray')

🤷‍♂️

**Comment by fzimmermann89** [comment]
Just putting a .cpu() before the abs fixes it.

Still not sure if this is a pytorch or a colab bug. 
Let's see what the pytorchs devs make of it https://github.com/pytorch/pytorch/issues/143440#issuecomment-2549823491

**Pull request merged**
